// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxGYuqnqHRjRjIaQXP0nAv5iJYpSBNnx0',
    appId: '1:608119249238:web:171ad85f71030ec214def7',
    messagingSenderId: '608119249238',
    projectId: 'pretech-website-3bdf0',
    authDomain: 'pretech-website-3bdf0.firebaseapp.com',
    storageBucket: 'pretech-website-3bdf0.firebasestorage.app',
    measurementId: 'G-JTP9K9Q1YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcaeGLMRYf0cdUUrlCTmxwiUUPbw1FERY',
    appId: '1:608119249238:android:293bcff04461276014def7',
    messagingSenderId: '608119249238',
    projectId: 'pretech-website-3bdf0',
    storageBucket: 'pretech-website-3bdf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgaoY0tfFL6KQ3iRLzGmEk89VmtprbNac',
    appId: '1:608119249238:ios:a0e82c774b3457be14def7',
    messagingSenderId: '608119249238',
    projectId: 'pretech-website-3bdf0',
    storageBucket: 'pretech-website-3bdf0.firebasestorage.app',
    iosBundleId: 'com.example.pretech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgaoY0tfFL6KQ3iRLzGmEk89VmtprbNac',
    appId: '1:608119249238:ios:a0e82c774b3457be14def7',
    messagingSenderId: '608119249238',
    projectId: 'pretech-website-3bdf0',
    storageBucket: 'pretech-website-3bdf0.firebasestorage.app',
    iosBundleId: 'com.example.pretech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxGYuqnqHRjRjIaQXP0nAv5iJYpSBNnx0',
    appId: '1:608119249238:web:552bf8ec86df158e14def7',
    messagingSenderId: '608119249238',
    projectId: 'pretech-website-3bdf0',
    authDomain: 'pretech-website-3bdf0.firebaseapp.com',
    storageBucket: 'pretech-website-3bdf0.firebasestorage.app',
    measurementId: 'G-F7J0DSET8C',
  );
}
